# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clrm1_cpp <- function(raw_ptr) {
    .Call('_clrm1_clrm1_cpp', PACKAGE = 'clrm1', raw_ptr)
}

